[environments]
  [environments.development]
    name = "aven-web-api"
    namespace = "aven"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = ""
    chart = ""
